-- MySQL Script generated by MySQL Workbench
-- Fri Aug 11 15:39:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `LibraryDB` ;

-- -----------------------------------------------------
-- Table `LibraryDB`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`book` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `b_title` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `b_author` VARCHAR(255) NOT NULL,
  `b_genre` VARCHAR(150) NOT NULL,
  `b_year` VARCHAR(4) NOT NULL,
  `b_quantity` SMALLINT(5) NOT NULL,
  `b_status` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`b_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`user` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_login` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `u_password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`rent` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `b_id` INT NOT NULL,
  `r_start` DATE NOT NULL,
  `r_end` DATE NOT NULL,
  `r_status` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`r_id`),
  INDEX `fk_rent_user1_idx` (`u_id` ASC),
  INDEX `fk_rent_book1_idx` (`b_id` ASC),
  CONSTRAINT `fk_rent_user1`
    FOREIGN KEY (`u_id`)
    REFERENCES `LibraryDB`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rent_book1`
    FOREIGN KEY (`b_id`)
    REFERENCES `LibraryDB`.`book` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `LibraryDB`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `LibraryDB`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryDB`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
